### ISSUE TITLE
Some transaction types result in "Proof doesn't validate as signature" when broadcasting

### ISSUE THREAD

**Issue by brunodb3** [iicc1/ledger-app-lto-network-unofficial#4]
Transaction types `cancel lease`, `mass transfer` and `anchor` result in a `Proof doesn't validate as signature` error when broadcasting. The ByteArray sent to the ledger app is correct according to the schema on the documentation, and yet, this error is shown.

You can replicate this error by going to the [Stakely.io demo](https://lto.stakely.io/) and attempting a `Cancel Lease` operation. This is what happens:

![image](https://user-images.githubusercontent.com/10848169/133080409-7d406187-2d11-468b-9c0e-9ff13538d4cc.png)

The same error was found when implementing the official Ledger support on the [lto-ui](https://github.com/ltonetwork/lto-ui) project.

**Comment by iicc1** [comment]
Fixed, he wasn't using v1 transactions.
